version: "3.8"
services: 
    application:
        image: cherrytreegee811/vision-vogue
        container_name: visionvogue-app
        hostname: localhost
        networks:
            - visionvogue-net
        ports:
            - 5000:5000
            - 5001:5001
        environment:
            ASPNETCORE_HTTP_PORT: https://+5001
            ASPNETCORE_URLS: http://+:5000
        depends_on:
            - database

    database:
        image: cherrytreegee811/vision-vogue-database
        container_name: sqlpreview
        hostname: localhost
        networks:
            - visionvogue-net
        ports:
            - 1433:1433
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: SATestPassword10*
networks:
    visionvogue-net:
        driver: bridge