name: VisionVogue .NET
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install Nikto
        shell: bash
        run: sudo apt install nikto

      - name: Install Nmap
        shell: bash
        run: sudo apt install nmap
          
      - name: Build Application And DB
        shell: bash
        run: docker compose up -d
        
      - name: Run Automated Tests
        shell: bash
        run: dotnet test VirtualGlassesProvider.Tests/VirtualGlassesProvider.Tests.csproj --os linux --verbosity minimal

      - name: Delete Test Data
        shell: bash
        run: docker exec -i sqlpreview /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${{ secrets.MSSQL_SA_SECRET }} -q "DELETE FROM VisionVogue.dbo.ASPNetUsers WHERE NormalizedUserName <> 'ADMIN';"

      - name: Nikto Scan
        shell: bash
        run: |
          nikto -h http://localhost:5000 -C all

      - name: Nmap Scan
        shell: bash
        run: sudo nmap -sT -p 1433,5000 --script vuln 127.0.0.1

      - name: Stop Containers
        shell: bash
        run: |
          docker stop visionvogue-app
          docker stop sqlpreview
        
      - name: Push to Docker
        if: ${{ github.ref == 'refs/heads/main' }}
        shell: bash
        run: |
          docker login -u cherrytreegee811 -p ${{ secrets.DOCKER_CRED }}
          docker commit sqlpreview cherrytreegee811/vision-vogue-database
          docker push cherrytreegee811/vision-vogue-database:latest
          docker push cherrytreegee811/vision-vogue:latest
