# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  
    inputs:
      environment:
              description: 'Environment to run tests against'
              type: environment
              required: true
jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: MyTestPassword
          ACCEPT_EULA: 'Y'
        ports:
          - 1433:1433
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    
    - name: Setup DB
      run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=SATestPassword" -e "MSSQL_PID=Developer" -p 1433:1433  --name sqlpreview -d mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    
    - name: List containers
      run: docker container ls

    - name: Confirm connectivity
      run: docker exec sqlpreview /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SATestPassword

    - name: Restore dependencies
      run: dotnet restore

    - name: Download tool
      run: dotnet tool install --global dotnet-ef
  
    - name: Add Migrations
      run: dotnet ef migrations add Initial -c GlassesStoreDbContext --project VirtualGlassesProvider/VirtualGlassesProvider.csproj

    - name: Update Database
      run: dotnet ef database update Initial --project VirtualGlassesProvider/VirtualGlassesProvider.csproj --connection "Server=sqlpreview,1433;Initial Catalog=MyTestDb;User Id=sa;Password=SATestPassword;"
      
    - name: Execute
      run: dotnet run --project VirtualGlassesProvider/VirtualGlassesProvider.csproj --launch-profile https
    - name: Test
      run: dotnet test VirtualGlassesProvider.Tests/VirtualGlassesProvider.Tests.csproj --verbosity normal
