# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to run tests against
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Setup DB
        run: docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=SATestPassword10*" --name sqlpreview --hostname localhost -p 1433:1433 -d mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
      
      - name: List containers
        run: docker container ls
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Download tool
        run: dotnet tool install --global dotnet-ef
      
      - name: Add Migrations
        run: dotnet ef migrations add Initial -c GlassesStoreDbContext --project VirtualGlassesProvider/VirtualGlassesProvider.csproj
      
      - name: Update Database
        run: dotnet ef database update Initial --project VirtualGlassesProvider/VirtualGlassesProvider.csproj --connection "Server=localhost,1433;Database=VisionVogue;User Id=sa;Password=SATestPassword10*;TrustServerCertificate=true;"
      
  execute:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Code
        run: dotnet run --project VirtualGlassesProvider/VirtualGlassesProvider.csproj --launch-profile https
    
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Test      
        run: dotnet test VirtualGlassesProvider.Tests/VirtualGlassesProvider.Tests.csproj --verbosity normal
  
